name: Dependencies Alignment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        react-version: [ 16.14.0, 17, 18 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        uses: prezly/setup-github-actions@v1
        with:
          node: ${{ matrix.node-version }}
          pnpm: "8.4.0"

      - name: Set React ${{ matrix.react-version }}
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          parse_json: true
          field: pnpm.overrides
          value: '{"@types/react":"${{ env.REACT_TYPES_VERSION }}","@types/react-dom":"${{ env.REACT_DOM_TYPES_VERSION }}","react":"${{ env.REACT_VERSION }}","react-dom":"${{ env.REACT_DOM_VERSION }}"}'
        env:
          REACT_TYPES_VERSION: ${{ matrix.react-version }}
          REACT_VERSION: ${{ matrix.react-version }}
          REACT_DOM_TYPES_VERSION: ${{ startsWith(matrix.react-version, '16.') && '16.9.9' || matrix.react-version }}
          REACT_DOM_VERSION: ${{ matrix.react-version }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --strict-peer-dependencies --ignore-pnpmfile --prod
